import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Abide Now",
  description: "Generated by create next app",
  metadataBase: new URL('https://abide-zeta.vercel.app/'), 
  openGraph: {
    title: "Abide Now",
    description: "Generated by create next app",
    url: 'https://abide-zeta.vercel.app/',
    siteName: 'Abide Now',
    images: [
      {
        url: '/images/hero-section-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Abide Now Preview Image',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: "Abide Now",
    description: "Generated by create next app",
    images: ['/images/hero-section-image.jpg'],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}